import { AlertTriangle, ArrowLeft, ArrowRight, Check, ShieldAlert } from 'lucide-react'
import { FormEvent, useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { api, post } from '../api'
import type { MinecraftVersionCatalog, Server } from '../types'

const steps = ['Identity', 'Resources', 'World rules', 'Review']
const initial = { name: '', slug: '', version: '26.2', server_type: 'VANILLA', memory_mb: 2048, cpu_limit: 2, max_players: 20, game_mode: 'survival', difficulty: 'normal', pvp: true, hardcore: false, view_distance: 10, simulation_distance: 10, motd: 'A Minecraft Server', world_seed: '', level_name: 'world', online_mode: true, offline_mode_confirmed: false, whitelist: '', operators: '', restart_policy: 'unless-stopped', port: '', eula_accepted: false }

export function CreateServerPage() {
  const navigate = useNavigate(); const [step, setStep] = useState(0); const [data, setData] = useState(initial); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [catalog, setCatalog] = useState<MinecraftVersionCatalog | null>(null); const [catalogError, setCatalogError] = useState('')
  useEffect(() => { api<MinecraftVersionCatalog>('/minecraft/versions').then(setCatalog).catch(() => setCatalogError('The live Mojang catalog is unavailable; common releases remain available.')) }, [])
  const update = (key: string, value: unknown) => setData(old => ({...old, [key]: value}))
  function autoSlug(name: string) { update('name', name); update('slug', name.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')) }
  async function submit(event: FormEvent) { event.preventDefault(); if (step < 3) { setStep(step + 1); return } setBusy(true); setError(''); try { const payload = {...data, port: data.port ? Number(data.port) : null, whitelist: data.whitelist.split(',').map(v => v.trim()).filter(Boolean), operators: data.operators.split(',').map(v => v.trim()).filter(Boolean)}; const server = await post<Server>('/servers', payload); navigate(`/servers/${server.id}`) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Creation failed') } finally { setBusy(false) } }
  return <div className="page narrow"><header className="page-header"><div><p className="eyebrow">Provisioning wizard</p><h1>Create a server</h1><p>Capacity is reserved even while this server is stopped.</p></div></header><ol className="steps">{steps.map((name, index) => <li key={name} className={index === step ? 'active' : index < step ? 'done' : ''}><span>{index < step ? <Check size={15}/> : index + 1}</span>{name}</li>)}</ol><form className="wizard panel" onSubmit={submit}>{error && <div className="form-error" role="alert">{error}</div>}
    {step === 0 && <section><h2>Name the world</h2><p>This identity is used in the dashboard and container labels.</p><div className="form-grid"><label>Display name<input value={data.name} onChange={e => autoSlug(e.target.value)} minLength={2} maxLength={100} required autoFocus/></label><label>URL-safe slug<input value={data.slug} onChange={e => update('slug', e.target.value)} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required/></label><label>Minecraft version<input list="minecraft-version-options" value={data.version} onChange={e => update('version', e.target.value)} maxLength={32} required/><datalist id="minecraft-version-options">{(catalog?.versions ?? [{id:'26.2'},{id:'26.1.1'},{id:'1.21.11'},{id:'1.21.4'},{id:'1.20.6'},{id:'1.20.4'},{id:'1.19.4'},{id:'1.18.2'},{id:'1.17.1'},{id:'1.16.5'},{id:'1.12.2'},{id:'1.8.9'}]).map(version => <option key={version.id} value={version.id}/>)}</datalist><small>{catalogError || (catalog ? catalog.source === 'mojang' ? `${catalog.versions.length} official versions from Mojang · latest release ${catalog.latest}` : 'Mojang is temporarily unavailable; common releases are shown.' : 'Loading every official Minecraft version…')} 26.x automatically uses Java 25.</small></label><label>Server type<select value={data.server_type} onChange={e => update('server_type', e.target.value)}><option>VANILLA</option><option>PAPER</option><option>FABRIC</option><option>FORGE</option></select></label><label className="span-2">Message of the day<input value={data.motd} onChange={e => update('motd', e.target.value)} maxLength={256}/></label></div></section>}
    {step === 1 && <section><h2>Reserve resources</h2><p>The Java heap is kept below the hard container limit to leave native memory overhead.</p><div className="form-grid"><label>Memory limit<select value={data.memory_mb} onChange={e => update('memory_mb', Number(e.target.value))}><option value={1024}>1 GB</option><option value={2048}>2 GB</option><option value={4096}>4 GB</option><option value={8192}>8 GB</option><option value={16384}>16 GB</option></select><small>At 2 GB, maximum heap is approximately 1536 MB.</small></label><label>CPU limit<input type="number" min="0.25" max="128" step="0.25" value={data.cpu_limit} onChange={e => update('cpu_limit', Number(e.target.value))}/></label><label>Maximum players<input type="number" min="1" max="1000" value={data.max_players} onChange={e => update('max_players', Number(e.target.value))}/></label><label>Port (optional)<input type="number" min="1024" max="65535" value={data.port} onChange={e => update('port', e.target.value)} placeholder="Automatic: 25565–26000"/></label><label>Restart policy<select value={data.restart_policy} onChange={e => update('restart_policy', e.target.value)}><option value="unless-stopped">Unless stopped</option><option value="on-failure">On failure</option><option value="no">Never</option></select></label></div></section>}
    {step === 2 && <section><h2>World & access</h2><div className="form-grid"><label>Game mode<select value={data.game_mode} onChange={e => update('game_mode', e.target.value)}><option>survival</option><option>creative</option><option>adventure</option><option>spectator</option></select></label><label>Difficulty<select value={data.difficulty} onChange={e => update('difficulty', e.target.value)}><option>peaceful</option><option>easy</option><option>normal</option><option>hard</option></select></label><label>Level name<input value={data.level_name} onChange={e => update('level_name', e.target.value)} required/></label><label>World seed<input value={data.world_seed} onChange={e => update('world_seed', e.target.value)} placeholder="Optional"/></label><label>View distance<input type="number" min="2" max="32" value={data.view_distance} onChange={e => update('view_distance', Number(e.target.value))}/></label><label>Simulation distance<input type="number" min="2" max="32" value={data.simulation_distance} onChange={e => update('simulation_distance', Number(e.target.value))}/></label><label className="span-2">Whitelist (comma separated)<input value={data.whitelist} onChange={e => update('whitelist', e.target.value)}/></label><label className="span-2">Operators (comma separated)<input value={data.operators} onChange={e => update('operators', e.target.value)}/></label></div><div className="checks"><label><input type="checkbox" checked={data.pvp} onChange={e => update('pvp', e.target.checked)}/> Enable PvP</label><label><input type="checkbox" checked={data.hardcore} onChange={e => update('hardcore', e.target.checked)}/> Hardcore mode</label><label><input type="checkbox" checked={data.online_mode} onChange={e => {update('online_mode', e.target.checked); if (e.target.checked) update('offline_mode_confirmed', false)}}/> Verify player accounts (online mode)</label></div>{!data.online_mode && <div className="notice danger"><ShieldAlert/><div><strong>Offline mode permits username impersonation</strong><span>A whitelist does not prevent impersonation. Do not expose this server publicly. Secure profiles will also be disabled.</span><label><input type="checkbox" checked={data.offline_mode_confirmed} onChange={e => update('offline_mode_confirmed', e.target.checked)} required/> I understand and accept this risk</label></div></div>}</section>}
    {step === 3 && <section><h2>Review & accept</h2><div className="review-grid"><div><span>Name</span><strong>{data.name}</strong></div><div><span>Runtime</span><strong>{data.server_type} {data.version}</strong></div><div><span>Reservation</span><strong>{data.memory_mb / 1024} GB · {data.cpu_limit} CPU</strong></div><div><span>Access</span><strong>{data.online_mode ? 'Verified accounts' : 'Offline mode'} · {data.port || 'Auto port'}</strong></div></div>{!data.online_mode && <div className="notice danger"><AlertTriangle/><div><strong>Offline-mode security warning remains active</strong><span>Anyone can impersonate a username, including an operator.</span></div></div>}<label className="eula-check"><input type="checkbox" checked={data.eula_accepted} onChange={e => update('eula_accepted', e.target.checked)} required/> I explicitly accept the <a href="https://aka.ms/MinecraftEULA" target="_blank" rel="noreferrer">Minecraft EULA</a> for this server.</label></section>}
    <footer className="wizard-actions"><button type="button" className="button secondary" disabled={step === 0 || busy} onClick={() => setStep(step - 1)}><ArrowLeft size={17}/> Back</button><button className="button primary" disabled={busy}>{step === 3 ? busy ? 'Creating…' : 'Create server' : <>Continue <ArrowRight size={17}/></>}</button></footer></form></div>
}
