import { Globe, Map as MapIcon, Upload } from 'lucide-react'
import { FormEvent, useEffect, useState } from 'react'
import { api, post } from '../api'
import { Empty, ErrorState, Loading } from '../components/States'
import type { Job, MapEntry, Server } from '../types'

export function MapsPage() {
  const [maps,setMaps] = useState<MapEntry[]|null>(null); const [servers,setServers]=useState<Server[]>([]); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [url,setUrl]=useState(''); const [name,setName]=useState(''); const [serverId,setServerId]=useState('')
  const load=()=>Promise.all([api<MapEntry[]>('/maps'),api<Server[]>('/servers')]).then(([m,s])=>{setMaps(m);setServers(s);if(!serverId&&s[0])setServerId(s[0].id)}).catch(e=>setError(e.message)); useEffect(()=>{load()},[])
  async function importUrl(e:FormEvent){e.preventDefault(); try{const job=await post<Job>('/maps/url',{url,name,description:'',author:null,minecraft_version:null});setMessage(`Import queued as job ${job.id.slice(0,8)}.`);setUrl('');setName('')}catch(reason){setMessage(reason instanceof Error?reason.message:'Import failed')}}
  async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);try{const job=await api<Job>('/maps/upload',{method:'POST',body:data});setMessage(`Upload queued as job ${job.id.slice(0,8)}.`);e.currentTarget.reset()}catch(reason){setMessage(reason instanceof Error?reason.message:'Upload failed')}}
  async function install(mapId:string){if(!serverId){setMessage('Choose a target server first.');return}try{await post(`/maps/${mapId}/install`,{server_id:serverId,restart_after_install:true});setMessage('Map installation queued. The current world will be backed up first.')}catch(reason){setMessage(reason instanceof Error?reason.message:'Install failed')}}
  return <div className="page"><header className="page-header"><div><p className="eyebrow">Curated worlds</p><h1>Map library</h1><p>Import administrator-supplied archives with size, path, and network safety checks.</p></div></header>{message&&<div className="notice">{message}</div>}<div className="dashboard-columns"><form className="panel" onSubmit={upload}><div className="panel-title"><div><p className="eyebrow">Local archive</p><h2>Upload a ZIP</h2></div><Upload/></div><label>Map name<input name="name" required maxLength={128}/></label><label>Description<textarea name="description" maxLength={2000}/></label><label>Minecraft version<input name="minecraft_version" placeholder="Optional"/></label><label>ZIP file<input name="file" type="file" accept=".zip,application/zip" required/></label><button className="button primary">Queue upload</button></form><form className="panel" onSubmit={importUrl}><div className="panel-title"><div><p className="eyebrow">Direct source</p><h2>Import from URL</h2></div><Globe/></div><label>Map name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Direct HTTPS URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com/world.zip" required/></label><div className="notice danger">Private networks, metadata endpoints, unsafe redirects, and unbounded downloads are blocked.</div><button className="button primary">Queue import</button></form></div><section className="panel map-section"><div className="panel-title"><div><p className="eyebrow">Validated archives</p><h2>Available maps</h2></div><label className="inline-select">Install target<select value={serverId} onChange={e=>setServerId(e.target.value)}><option value="">Choose server</option>{servers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div>{error?<ErrorState message={error} retry={load}/>:maps===null?<Loading/>:maps.length===0?<Empty title="No maps yet" detail="Upload a ZIP or provide a direct URL to begin."/>:<div className="card-grid">{maps.map(map=><article className="map-card" key={map.id}><div className="map-visual"><MapIcon/></div><StatusBadge status={map.compatibility_status}/><h3>{map.name}</h3><p>{map.description||'No description provided.'}</p><small>{map.author||'Unknown author'} · {(map.file_size/1e6).toFixed(1)} MB · {map.minecraft_version||'Version unverified'}</small><button className="button secondary wide" onClick={()=>void install(map.id)}>Back up & install</button></article>)}</div>}</section></div>
}

function StatusBadge({status}:{status:string}){return <span className={`status status-${status}`}>{status}</span>}
