import { Archive, ArrowLeft, CircleStop, Download, Play, RefreshCw, Send, Settings, Skull, Terminal, Trash2 } from 'lucide-react'
import { FormEvent, useCallback, useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api, patch, post, remove } from '../api'
import { ServerAddress } from '../components/ServerAddress'
import { ErrorState, Loading } from '../components/States'
import { StatusBadge } from '../components/StatusBadge'
import type { Backup, Server } from '../types'

type Tab = 'overview' | 'console' | 'logs' | 'configuration' | 'backups' | 'danger'

export function ServerDetailPage() {
  const { id = '' } = useParams(); const [server, setServer] = useState<Server | null>(null); const [tab, setTab] = useState<Tab>('overview'); const [error, setError] = useState(''); const [busy, setBusy] = useState('')
  const load = useCallback(() => api<Server>(`/servers/${id}`).then(setServer).catch(e => setError(e.message)), [id])
  useEffect(() => { load(); const timer = window.setInterval(load, 10000); return () => clearInterval(timer) }, [load])
  async function action(name: string, confirmation?: string) { setBusy(name); setError(''); try { const result = await post<Server>(`/servers/${id}/${name}`, confirmation ? {confirmation} : {}); setServer(result) } catch (e) { setError(e instanceof Error ? e.message : 'Operation failed') } finally { setBusy('') } }
  if (error && !server) return <div className="page"><ErrorState message={error} retry={load}/></div>
  if (!server) return <div className="page"><Loading label="Opening server"/></div>
  return <div className="page"><Link className="back-link" to="/servers"><ArrowLeft size={16}/> All servers</Link><header className="server-heading"><div className="server-avatar xl">{server.name.slice(0, 2).toUpperCase()}</div><div><div className="heading-line"><h1>{server.name}</h1><StatusBadge status={server.status}/></div><p>{server.server_type} {server.version} · {server.memory_mb / 1024} GB</p><ServerAddress port={server.port} compact/></div><div className="header-actions">{server.status === 'running' ? <><button className="button secondary" disabled={!!busy} onClick={() => void action('restart')}><RefreshCw size={16}/> Restart</button><button className="button danger" disabled={!!busy} onClick={() => void action('stop')}><CircleStop size={16}/> Stop</button></> : <button className="button primary" disabled={!!busy} onClick={() => void action('start')}><Play size={16}/> Start server</button>}</div></header>{error && <div className="form-error">{error}</div>}<nav className="tabs" aria-label="Server sections">{(['overview','console','logs','configuration','backups','danger'] as Tab[]).map(name => <button key={name} className={tab === name ? 'active' : ''} onClick={() => setTab(name)}>{name}</button>)}</nav>
    {tab === 'overview' && <Overview server={server}/>} {tab === 'console' && <ConsolePanel id={id}/>} {tab === 'logs' && <LogsPanel id={id} slug={server.slug}/>} {tab === 'configuration' && <ConfigPanel server={server} onSaved={setServer}/>} {tab === 'backups' && <ServerBackups id={id}/>} {tab === 'danger' && <DangerZone server={server} onForce={name => action('force-stop', name)}/>} </div>
}

function Overview({server}: {server: Server}) { const uptime = server.last_started_at ? Math.max(0, Date.now() - new Date(server.last_started_at).getTime()) : 0; return <div className="detail-grid"><section className="panel"><p className="eyebrow">Runtime</p><h2>Current state</h2><dl className="details"><div><dt>Status</dt><dd><StatusBadge status={server.status}/></dd></div><div><dt>Health</dt><dd>{server.status === 'running' ? 'Checking live health' : 'Not running'}</dd></div><div><dt>Uptime</dt><dd>{server.status === 'running' ? `${Math.floor(uptime / 3600000)}h ${Math.floor(uptime / 60000) % 60}m` : '—'}</dd></div><div><dt>Last error</dt><dd>{server.last_error ?? 'None'}</dd></div></dl></section><section className="panel"><p className="eyebrow">World rules</p><h2>Player experience</h2><dl className="details"><div><dt>Mode</dt><dd>{server.game_mode}</dd></div><div><dt>Difficulty</dt><dd>{server.difficulty}</dd></div><div><dt>Players</dt><dd>0 / {server.max_players}</dd></div><div><dt>Account verification</dt><dd>{server.online_mode ? 'Enabled' : 'OFF — impersonation risk'}</dd></div></dl></section><section className="panel span-2"><p className="eyebrow">Capacity reservation</p><h2>{(server.memory_mb / 1024).toFixed(1)} GB memory · {server.cpu_limit} CPU</h2><p>Java heap is automatically capped at approximately 75% of the container limit, leaving room for native memory and container overhead.</p></section></div> }

function ConsolePanel({id}: {id: string}) { const [command, setCommand] = useState(''); const [lines, setLines] = useState<string[]>(['Console ready. Commands are sent over private RCON.']); const [busy, setBusy] = useState(false); async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); try { const result = await post<{output:string}>(`/servers/${id}/console`, {command}); setLines(old => [...old, `> ${command}`, result.output]); setCommand('') } catch (reason) { setLines(old => [...old, `Error: ${reason instanceof Error ? reason.message : 'command failed'}`]) } finally { setBusy(false) } } return <section className="panel console-panel"><div className="panel-title"><div><p className="eyebrow">Private RCON</p><h2>Live console</h2></div><Terminal/></div><pre aria-live="polite">{lines.join('\n')}</pre><form onSubmit={submit}><span>&gt;</span><input value={command} onChange={e => setCommand(e.target.value)} placeholder="say Hello world" required maxLength={512}/><button className="button primary" disabled={busy}><Send size={16}/> Send</button></form></section> }

function LogsPanel({id, slug}: {id: string; slug: string}) { const [logs, setLogs] = useState(''); const [error, setError] = useState(''); const load = useCallback(() => api<{logs:string}>(`/servers/${id}/logs?tail=1000`).then(r => {setLogs(r.logs);setError('')}).catch(e => setError(e.message)), [id]); useEffect(() => {void load()}, [load]); return <section className="panel console-panel"><div className="panel-title"><div><p className="eyebrow">Container output</p><h2>Recent logs</h2></div><div className="header-actions"><button className="button secondary" onClick={() => void load()}><RefreshCw size={16}/> Refresh</button><a className="button secondary" href={`/api/v1/servers/${id}/logs/download`} download={`${slug}.log`}><Download size={16}/> Download</a></div></div>{error ? <ErrorState message={error} retry={() => void load()}/> : <pre>{logs || 'No log lines available.'}</pre>}</section> }

function ConfigPanel({server, onSaved}: {server: Server; onSaved: (s: Server) => void}) { const [form, setForm] = useState({motd: server.motd, max_players: server.max_players, view_distance: server.view_distance, simulation_distance: server.simulation_distance, pvp: server.pvp, hardcore: server.hardcore, game_mode: server.game_mode, difficulty: server.difficulty, restart_policy: server.restart_policy}); const [message, setMessage] = useState(''); async function save(e: FormEvent) { e.preventDefault(); try { onSaved(await patch<Server>(`/servers/${server.id}`, form)); setMessage('Configuration saved. Recreate or restart the server when needed.') } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'Save failed') } } return <form className="panel" onSubmit={save}><div className="panel-title"><div><p className="eyebrow">Safe allowlist</p><h2>Configuration editor</h2></div><Settings/></div>{message && <div className="notice">{message}</div>}<div className="form-grid"><label className="span-2">Message of the day<input value={form.motd} onChange={e => setForm({...form,motd:e.target.value})}/></label><label>Maximum players<input type="number" min="1" max="1000" value={form.max_players} onChange={e => setForm({...form,max_players:Number(e.target.value)})}/></label><label>Game mode<select value={form.game_mode} onChange={e => setForm({...form,game_mode:e.target.value})}><option>survival</option><option>creative</option><option>adventure</option><option>spectator</option></select></label><label>Difficulty<select value={form.difficulty} onChange={e => setForm({...form,difficulty:e.target.value})}><option>peaceful</option><option>easy</option><option>normal</option><option>hard</option></select></label><label>Restart policy<select value={form.restart_policy} onChange={e => setForm({...form,restart_policy:e.target.value})}><option value="unless-stopped">Unless stopped</option><option value="on-failure">On failure</option><option value="no">Never</option></select></label><label>View distance<input type="number" min="2" max="32" value={form.view_distance} onChange={e => setForm({...form,view_distance:Number(e.target.value)})}/></label><label>Simulation distance<input type="number" min="2" max="32" value={form.simulation_distance} onChange={e => setForm({...form,simulation_distance:Number(e.target.value)})}/></label></div><div className="checks"><label><input type="checkbox" checked={form.pvp} onChange={e => setForm({...form,pvp:e.target.checked})}/> PvP</label><label><input type="checkbox" checked={form.hardcore} onChange={e => setForm({...form,hardcore:e.target.checked})}/> Hardcore</label></div><button className="button primary">Save configuration</button></form> }

function ServerBackups({id}: {id:string}) { const [items,setItems] = useState<Backup[]>([]); const [message,setMessage] = useState(''); const load = useCallback(() => api<Backup[]>(`/backups?server_id=${id}`).then(setItems), [id]); useEffect(() => {void load()}, [load]); async function create() { await post(`/backups/servers/${id}`, {reason:'manual'}); setMessage('Backup queued. Progress is available under Background jobs.') } return <section className="panel"><div className="panel-title"><div><p className="eyebrow">Recovery</p><h2>Backups</h2></div><button className="button primary" onClick={() => void create()}><Archive size={16}/> Create backup</button></div>{message && <div className="notice">{message}</div>}<div className="table"><div className="table-head"><span>Date</span><span>Reason</span><span>Size</span><span/></div>{items.map(b => <div key={b.id}><span>{new Date(b.created_at).toLocaleString()}</span><span>{b.reason}</span><span>{(b.file_size/1e6).toFixed(1)} MB</span><span><a href={`/api/v1/backups/${b.id}/download`} aria-label="Download backup"><Download size={17}/></a></span></div>)}</div></section> }

function DangerZone({server, onForce}: {server:Server; onForce:(name:string)=>Promise<unknown>}) { const [confirmation,setConfirmation] = useState(''); const [message,setMessage] = useState(''); async function deleteContainer() { try { await remove(`/servers/${server.id}`); setMessage('Container deleted. Server data is preserved and recoverable.') } catch(e) { setMessage(e instanceof Error ? e.message : 'Deletion failed') } } async function deleteData() { try { await remove(`/servers/${server.id}/data`, {confirmation}); setMessage('Container data was permanently deleted and is not recoverable from this application.') } catch(e) { setMessage(e instanceof Error ? e.message : 'Deletion failed') } } return <section className="panel danger-zone"><p className="eyebrow">Destructive actions</p><h2>Danger zone</h2>{message && <div className="notice danger">{message}</div>}<div><span><strong>Force stop</strong><small>Immediately terminates the process. Unsaved world data may be lost.</small></span><button className="button danger" onClick={() => void onForce(server.name)}><Skull size={16}/> Force stop</button></div><div><span><strong>Delete container, preserve data</strong><small>The world and all persistent files remain recoverable.</small></span><button className="button danger" onClick={() => void deleteContainer()}><Trash2 size={16}/> Delete container</button></div><div><span><strong>Permanently delete all data</strong><small>First delete the container, then type <b>{server.name}</b>. This cannot be recovered unless an external backup exists.</small><input value={confirmation} onChange={e=>setConfirmation(e.target.value)} placeholder={server.name}/></span><button className="button danger" disabled={confirmation !== server.name} onClick={() => void deleteData()}><Trash2 size={16}/> Permanently delete</button></div></section> }
